import { Comment } from '../../../shared/model/comment';

export const mock: Comment[] = [
  {
    id: 'sdfbg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '1st comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '1',
    commentTreePath: '1',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'fsgfdnh',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '2nd comment: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    contentStatus: 'ACTIVE',
    commentTreeId: '2',
    commentTreePath: '2',
    belongsToId: '2',
    confessionId: '1',
  },
  {
    id: 'sddvfbnfbg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '1st reply to 1st comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '3',
    commentTreePath: '1/3',
    belongsToId: '2',
    confessionId: '1',
  },
  {
    id: 'dvfbent',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '3rd comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '4',
    commentTreePath: '4',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'njbglkmrbgf',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '2nd reply 1st comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '5',
    commentTreePath: '1/5',
    belongsToId: '2',
    confessionId: '1',
  },
  {
    id: 'fdgfhgf',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '4th comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '6',
    commentTreePath: '6',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'sdfbg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '1st reply 2nd comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '7',
    commentTreePath: '2/7',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dsgfhdghfg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '3rd reply 1st comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '8',
    commentTreePath: '1/8',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dsgfhdghfg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '3rd reply 1st comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '8',
    commentTreePath: '1/8/1',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dfsdgfhgf',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '1st nested reply 2nd reply 1st comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '9',
    commentTreePath: '1/3/9',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'hijdklfgh',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '2nd nested reply 2nd reply 1st comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '10',
    commentTreePath: '1/3/9/10',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dfghgfsdghgfd',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: '1st reply 4th comment',
    contentStatus: 'ACTIVE',
    commentTreeId: '11',
    commentTreePath: '6/11',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dasfg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: 'fuck knows',
    contentStatus: 'ACTIVE',
    commentTreeId: '11',
    commentTreePath: '1/3/6',
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dasfg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: 'fuck knows',
    contentStatus: 'ACTIVE',
    commentTreeId: '11',
    commentTreePath: '1/3/6/2', // TODO: Order is wrong because it's sorting strings not numbers e.g 1,11,2
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dasfg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: 'fuck knows',
    contentStatus: 'ACTIVE',
    commentTreeId: '11',
    commentTreePath: '1/3/6/2/1', // TODO: Order is wrong because it's sorting strings not numbers e.g 1,11,2
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dasfg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: 'fuck knowsLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    contentStatus: 'ACTIVE',
    commentTreeId: '11',
    commentTreePath: '1/3/6/2/1/1', // TODO: Order is wrong because it's sorting strings not numbers e.g 1,11,2
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dasfg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: 'fuck knows',
    contentStatus: 'ACTIVE',
    commentTreeId: '11',
    commentTreePath: '1/3/6/2/1/2', // TODO: Order is wrong because it's sorting strings not numbers e.g 1,11,2
    belongsToId: '1',
    confessionId: '1',
  },
  {
    id: 'dasfg',
    createdAt: String(new Date('2024-02-15T23:12:38.894Z')),
    body: 'fuck knows',
    contentStatus: 'ACTIVE',
    commentTreeId: '11',
    commentTreePath: '1/3/6/3', // TODO: Order is wrong because it's sorting strings not numbers e.g 1,11,2
    belongsToId: '1',
    confessionId: '1',
  },
];
